# Generated by Django 3.2.13 on 2022-11-21 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('audience', models.IntegerField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=128)),
                ('score', models.FloatField()),
                ('poster_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exp_reple', models.TextField()),
                ('like_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendMovie',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.TextField()),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=128)),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('media_type', models.CharField(max_length=128)),
                ('genre_ids', models.CharField(max_length=128)),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField()),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='One_line_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, null=True)),
                ('grade', models.FloatField()),
                ('like_comment_users', models.ManyToManyField(blank=True, related_name='like_comment_users', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
